version: 2

multi-ecosystem-groups:
  project-updates:
    schedule:
      interval: "cron"
      cronjob: "15 1 * * 0"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    multi-ecosystem-group: "project-updates"
    patterns:
      - "*"
    commit-message:
      prefix: "[GITHUB-ACTIONS] "
    cooldown:
      default-days: 3
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "project-updates"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    versioning-strategy: increase
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "[UV] "
    patterns:
      - "*"
    cooldown:
      default-days: 3
  - package-ecosystem: "pip"
    directory: "/"
    multi-ecosystem-group: "project-updates"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    versioning-strategy: increase
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "[PIP] "
    patterns:
      - "*"
    cooldown:
      default-days: 3
